Add support for cpanfile-based dependencies

diff --git a/5.16/.sti/bin/assemble b/5.16/.sti/bin/assemble
--- a/5.16/.sti/bin/assemble
+++ b/5.16/.sti/bin/assemble
@@ -1,36 +1,47 @@
-#!/bin/bash -ue
+#!/bin/bash
 
 source scl_source enable perl516
 
-EXCLUDED_PRAGMAS=("perl" "strict" "warnings" "constant" "open" "lib" "vars" "base" "utf8")
-DEPS=$(find . -type f \( -name \*\.pm -o -name \*\.pl \); )
+set -eu
 
-for f in $(( echo "$DEPS" | xargs /usr/lib/rpm/perl.req | awk '{ print $1 }' | sed 's/^perl(\(.*\))$/\1/'; cat ${CPAN_PATH} 2>/dev/null ) | sort -u | grep . )
-do
-	# Skipping well-known perl pragmas
-	for element in ${EXCLUDED_PRAGMAS[@]}; do
-		[[ $element == $f ]] && continue 2
-	done
+echo "---> Installing application source"
+cp -Rf /tmp/src/* ./
 
-	DISABLE_TEST="-n"
-	if [ -z "${ENABLE_CPAN_TESTS} ]
-	then
-		echo ".openshift/markers/enable_cpan_tests!  enabling default cpan tests" 1>&2
-		DISABLE_TEST=""
-	fi
 
-	# Do not error the build when the CPAN module failed to install, but report
-	# it to user. This will allow modules that are not local, nor CPAN to pass
-	# the build.
-	cpanm $DISABLE_TEST $MIRROR -L ${OPENSHIFT_PERL_DIR}perl5lib "$f"
-
-done
+# TODO
+MIRROR=
 
 # Installing dependencies with cpanfile
 if [ -f "cpanfile" ]
 then
-	echo "***  Installing modules from cpanfile"
-	pushd ${OPENSHIFT_REPO_DIR}.openshift > /dev/null
-	cpanm $MIRROR -L ${OPENSHIFT_PERL_DIR}perl5lib --installdeps .
-	popd > /dev/null
+	echo "---> Installing modules from cpanfile"
+	perl cpanm $MIRROR --notest -l extlib Module::CoreList
+	perl -Iextlib/lib/perl5 cpanm $MIRROR --notest -L extlib --installdeps .
+else
+	echo "---> No cpanfile found, exiting"
+	exit 1
+#	TODO: Should we support this? If yes, we need to install rpm-build for /usr/lib/rpm/perl.req
+#	EXCLUDED_PRAGMAS=("perl" "strict" "warnings" "constant" "open" "lib" "vars" "base" "utf8")
+#	DEPS=$(find . -type f -name '*.p[ml]')
+#
+#	for f in $(echo "$DEPS" | xargs /usr/lib/rpm/perl.req | awk '{ print $1 }' | sed 's/^perl(\(.*\))$/\1/' | sort -u | grep .)
+#	do
+#		# Skipping well-known perl pragmas
+#		for element in ${EXCLUDED_PRAGMAS[@]}; do
+#			[[ $element == $f ]] && continue 2
+#		done
+#
+#		DISABLE_TEST="-n"
+#		if [ -z "${ENABLE_CPAN_TESTS}" ]
+#		then
+#			echo ".openshift/markers/enable_cpan_tests!  enabling default cpan tests" 1>&2
+#			DISABLE_TEST=""
+#		fi
+#
+#		# Do not error the build when the CPAN module failed to install, but report
+#		# it to user. This will allow modules that are not local, nor CPAN to pass
+#		# the build.
+#		cpanm $DISABLE_TEST $MIRROR -L ${OPENSHIFT_PERL_DIR}extlib "$f"
+#
+#	done
 fi
